services:
  solace:
    image: solace/solace-pubsub-standard:latest
    container_name: solace
    ports:
      - "8080:8080"    # PubSub+ Manager UI
      - "55555:55555"  # SMF
      - "1883:1883"    # MQTT (optional)
      - "5672:5672"    # AMQP (optional)
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
    shm_size: 1g
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

